import { app, dialog, BrowserWindow } from 'electron';
import { promises as fs } from 'fs';
import path from 'path';
import { execFile } from 'child_process';
import { promisify } from 'util';
import conf, { Server, ServerGroup } from './conf';
import { getHostPassword, setHostPassword, hostPasswordsFilePath } from './hostSecrets';
import { v4 as uuidv4 } from 'uuid';

const execFileAsync = promisify(execFile);

const FORMAT = 'sguala-bundle';
const FORMAT_VERSION = 1;

type Manifest = {
  format: string;
  version: number;
  created_at: string;
  source: string;
  include_secrets: boolean;
  include_keys: boolean;
  app_version?: string;
};

type HostSpec = {
  name: string;
  hostname: string;
  port: number;
  user: string;
  auth: string;
  identity_file?: string;
  key_ref?: string;
  proxy_jump?: string;
  has_password?: boolean;
};

type HostsFile = {
  version: number;
  groups: { name: string; hosts: HostSpec[] }[];
};

export type BundleExportOpts = {
  includeKeys?: boolean;
  includeSecrets?: boolean;
};

export type BundleImportOpts = {
  overwrite?: boolean;
  includeKeys?: boolean;
  includeSecrets?: boolean;
};

function sanitizeFileName(s: string): string {
  const out = (s || 'key').replace(/[^a-zA-Z0-9._-]/g, '_');
  return out || 'key';
}

function looksLikePrivateKey(s: string): boolean {
  return typeof s === 'string' && s.includes('PRIVATE KEY');
}

async function writeJSON(filePath: string, data: unknown): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true, mode: 0o700 });
  await fs.writeFile(filePath, JSON.stringify(data, null, 2) + '\n', { mode: 0o600 });
}

async function readJSON<T>(filePath: string): Promise<T> {
  const raw = await fs.readFile(filePath, 'utf8');
  return JSON.parse(raw) as T;
}

function renderSSHFragment(hf: HostsFile): string {
  let out = '# Generated by sguala-bundle — do not store passwords here\n';
  for (const g of hf.groups || []) {
    if (g.name && g.name !== 'Default') {
      out += `\n# ${g.name}\n`;
    }
    for (const h of g.hosts || []) {
      out += `Host ${h.name}\n`;
      if (h.hostname && h.hostname !== h.name) {
        out += `  HostName ${h.hostname}\n`;
      }
      if (h.user) out += `  User ${h.user}\n`;
      if (h.port && h.port !== 22) out += `  Port ${h.port}\n`;
      const id = h.identity_file || h.key_ref;
      if (id) out += `  IdentityFile ${id}\n`;
      if (h.proxy_jump) out += `  ProxyJump ${h.proxy_jump}\n`;
      out += '\n';
    }
  }
  return out;
}

async function buildHostsFromConf(): Promise<{
  hostsFile: HostsFile;
  passwords: Record<string, string>;
  keys: Record<string, string>;
}> {
  const c = conf.get();
  const passwords: Record<string, string> = {};
  const keys: Record<string, string> = {};
  const groups: HostsFile['groups'] = [];

  for (const g of c.groups || []) {
    const hosts: HostSpec[] = [];
    for (const s of g.servers || []) {
      let auth = 'agent';
      if (s.usePassword) auth = 'password';
      else if (s.privateKey) auth = 'key';

      let hasPassword = false;
      const pw = await getHostPassword(s.name);
      if (pw) {
        passwords[s.name] = pw;
        hasPassword = true;
      } else if (s.password) {
        passwords[s.name] = s.password;
        hasPassword = true;
      }

      const spec: HostSpec = {
        name: s.name,
        hostname: s.host,
        port: s.port || 22,
        user: s.username || 'root',
        auth,
        has_password: hasPassword,
      };

      if (s.useHop && s.hopServerUuid) {
        const hop = conf.getServer(s.hopServerUuid);
        if (hop?.name) spec.proxy_jump = hop.name;
      }

      if (s.privateKey && looksLikePrivateKey(s.privateKey)) {
        const safe = sanitizeFileName(s.name);
        spec.key_ref = `secrets/keys/${safe}.pem`;
        keys[safe] = s.privateKey;
      }

      hosts.push(spec);
    }
    groups.push({ name: g.name || 'Default', hosts });
  }

  return { hostsFile: { version: 1, groups }, passwords, keys };
}

async function writeBundleDir(
  root: string,
  opts: BundleExportOpts,
): Promise<void> {
  const { hostsFile, passwords, keys } = await buildHostsFromConf();
  const includeKeys = !!opts.includeKeys;
  const includeSecrets = !!opts.includeSecrets;

  const manifest: Manifest = {
    format: FORMAT,
    version: FORMAT_VERSION,
    created_at: new Date().toISOString(),
    source: 'desktop',
    include_secrets: includeSecrets,
    include_keys: includeKeys,
    app_version: app.getVersion?.() || '2.1.0',
  };

  await fs.mkdir(root, { recursive: true, mode: 0o700 });
  await writeJSON(path.join(root, 'manifest.json'), manifest);
  await writeJSON(path.join(root, 'hosts.json'), hostsFile);
  await fs.mkdir(path.join(root, 'ssh'), { recursive: true, mode: 0o700 });
  await fs.writeFile(path.join(root, 'ssh', 'config.fragment'), renderSSHFragment(hostsFile), { mode: 0o600 });
  await fs.writeFile(
    path.join(root, 'README.txt'),
    'sguala-bundle\nRestore with desktop Import Bundle or: sguala import <path>\n',
    { mode: 0o644 },
  );

  if (includeSecrets && Object.keys(passwords).length) {
    await writeJSON(path.join(root, 'secrets', 'passwords.json'), {
      version: 1,
      hosts: passwords,
    });
  }
  if (includeKeys && Object.keys(keys).length) {
    const keyDir = path.join(root, 'secrets', 'keys');
    await fs.mkdir(keyDir, { recursive: true, mode: 0o700 });
    for (const [name, pem] of Object.entries(keys)) {
      await fs.writeFile(path.join(keyDir, `${name}.pem`), pem, { mode: 0o600 });
    }
  }
}

async function zipWithPython(srcDir: string, zipPath: string): Promise<void> {
  const script = `
import zipfile, os, sys
src, dest = sys.argv[1], sys.argv[2]
with zipfile.ZipFile(dest, 'w', zipfile.ZIP_DEFLATED) as z:
    for root, dirs, files in os.walk(src):
        for f in files:
            p = os.path.join(root, f)
            z.write(p, os.path.relpath(p, src))
`;
  await execFileAsync('python3', ['-c', script, srcDir, zipPath]);
}

async function unzipWithPython(zipPath: string, dest: string): Promise<void> {
  const script = `
import zipfile, sys
zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])
`;
  await fs.mkdir(dest, { recursive: true });
  await execFileAsync('python3', ['-c', script, zipPath, dest]);
}

export async function exportBundleDialog(
  win: BrowserWindow | null,
  opts: BundleExportOpts,
): Promise<{ type: string; path?: string; message?: string }> {
  const { filePath, canceled } = await dialog.showSaveDialog(win || undefined, {
    title: 'Export sguala bundle',
    defaultPath: path.join(app.getPath('documents'), 'sguala-bundle.zip'),
    filters: [
      { name: 'sguala zip', extensions: ['zip'] },
      { name: 'All', extensions: ['*'] },
    ],
  });
  if (canceled || !filePath) {
    return { type: 'cancel' };
  }
  try {
    const tmp = path.join(app.getPath('temp'), `sguala-bundle-${Date.now()}`);
    await writeBundleDir(tmp, opts);
    if (filePath.toLowerCase().endsWith('.zip')) {
      try {
        await zipWithPython(tmp, filePath);
      } catch {
        // fallback: copy as directory beside zip name
        const dirPath = filePath.replace(/\.zip$/i, '');
        await fs.cp(tmp, dirPath, { recursive: true });
        await fs.rm(tmp, { recursive: true, force: true });
        return { type: 'ok', path: dirPath, message: 'zip unavailable; wrote directory instead' };
      }
    } else {
      await fs.cp(tmp, filePath, { recursive: true });
    }
    await fs.rm(tmp, { recursive: true, force: true });
    return { type: 'ok', path: filePath };
  } catch (e: any) {
    return { type: 'error', message: e?.message || String(e) };
  }
}

async function resolveBundleRoot(selected: string): Promise<{ root: string; cleanup: () => Promise<void> }> {
  const st = await fs.stat(selected);
  if (st.isDirectory()) {
    return { root: selected, cleanup: async () => {} };
  }
  if (!selected.toLowerCase().endsWith('.zip')) {
    throw new Error('Select a bundle directory or .zip file');
  }
  const tmp = path.join(app.getPath('temp'), `sguala-import-${Date.now()}`);
  await unzipWithPython(selected, tmp);
  let root = tmp;
  const entries = await fs.readdir(tmp, { withFileTypes: true });
  if (entries.length === 1 && entries[0].isDirectory()) {
    root = path.join(tmp, entries[0].name);
  }
  return {
    root,
    cleanup: async () => {
      await fs.rm(tmp, { recursive: true, force: true });
    },
  };
}

export async function importBundleDialog(
  win: BrowserWindow | null,
  opts: BundleImportOpts,
): Promise<{ type: string; message?: string; added?: number; skipped?: number; updated?: number }> {
  const { canceled, filePaths } = await dialog.showOpenDialog(win || undefined, {
    title: 'Import sguala bundle',
    properties: ['openFile', 'openDirectory'],
    filters: [
      { name: 'Bundle', extensions: ['zip', 'json'] },
      { name: 'All', extensions: ['*'] },
    ],
  });
  if (canceled || !filePaths?.length) {
    return { type: 'cancel' };
  }
  let selected = filePaths[0];
  // if user picked manifest.json, use parent
  if (selected.endsWith('manifest.json') || selected.endsWith('hosts.json')) {
    selected = path.dirname(selected);
  }
  try {
    const { root, cleanup } = await resolveBundleRoot(selected);
    try {
      const result = await importBundleFromRoot(root, opts);
      return { type: 'ok', ...result };
    } finally {
      await cleanup();
    }
  } catch (e: any) {
    return { type: 'error', message: e?.message || String(e) };
  }
}

async function importBundleFromRoot(
  root: string,
  opts: BundleImportOpts,
): Promise<{ message: string; added: number; skipped: number; updated: number }> {
  const includeKeys = opts.includeKeys !== false;
  const includeSecrets = opts.includeSecrets !== false;
  const overwrite = !!opts.overwrite;

  const manifest = await readJSON<Manifest>(path.join(root, 'manifest.json'));
  if (manifest.format !== FORMAT) {
    throw new Error(`unsupported format: ${manifest.format}`);
  }
  const hostsFile = await readJSON<HostsFile>(path.join(root, 'hosts.json'));

  let passwords: Record<string, string> = {};
  try {
    const pf = await readJSON<{ hosts?: Record<string, string> }>(
      path.join(root, 'secrets', 'passwords.json'),
    );
    passwords = pf.hosts || {};
  } catch {
    /* optional */
  }

  const keyMap: Record<string, string> = {};
  try {
    const keyDir = path.join(root, 'secrets', 'keys');
    const files = await fs.readdir(keyDir);
    for (const f of files) {
      if (!f.endsWith('.pem') && !f.includes('KEY')) continue;
      const base = path.basename(f, path.extname(f));
      keyMap[base] = await fs.readFile(path.join(keyDir, f), 'utf8');
    }
  } catch {
    /* optional */
  }

  const c = conf.get();
  const nameToServer = new Map<string, Server>();
  for (const g of c.groups) {
    for (const s of g.servers) {
      nameToServer.set(s.name, s);
    }
  }

  let added = 0;
  let skipped = 0;
  let updated = 0;

  // First pass: ensure all hosts exist (for hop wiring)
  const pendingHops: { server: Server; jump: string }[] = [];

  for (const g of hostsFile.groups || []) {
    let group = c.groups.find((x) => x.name === g.name);
    if (!group) {
      group = new ServerGroup();
      group.name = g.name || 'Default';
      group.servers = [];
      c.groups.push(group);
    }

    for (const h of g.hosts || []) {
      const existing = nameToServer.get(h.name);
      if (existing && !overwrite) {
        skipped++;
        continue;
      }

      let server: Server;
      if (existing && overwrite) {
        server = existing;
        updated++;
      } else {
        server = new Server();
        server.uuid = uuidv4();
        group.servers.push(server);
        nameToServer.set(h.name, server);
        added++;
      }

      server.name = h.name;
      server.host = h.hostname || h.name;
      server.port = h.port || 22;
      server.username = h.user || 'root';
      server.usePassword = h.auth === 'password' || !!h.has_password;
      server.useHop = false;
      server.hopServerUuid = undefined;

      if (includeKeys) {
        const safe = sanitizeFileName(h.name);
        const pem = keyMap[safe] || (h.key_ref ? keyMap[sanitizeFileName(path.basename(h.key_ref, path.extname(h.key_ref)))] : '');
        if (pem) {
          server.privateKey = pem;
          server.usePassword = false;
        }
      }

      if (includeSecrets && passwords[h.name]) {
        await setHostPassword(h.name, passwords[h.name]);
        server.usePassword = true;
        server.password = undefined;
      }

      if (h.proxy_jump) {
        pendingHops.push({ server, jump: h.proxy_jump });
      }
    }
  }

  for (const { server, jump } of pendingHops) {
    const hop = nameToServer.get(jump);
    if (hop) {
      server.useHop = true;
      server.hopServerUuid = hop.uuid;
    }
  }

  await conf.store(c);
  await conf.load();

  return {
    message: `added ${added}, updated ${updated}, skipped ${skipped}`,
    added,
    skipped,
    updated,
  };
}

/** Expose passwords file path for diagnostics in UI. */
export function passwordsFileHint(): string {
  return hostPasswordsFilePath();
}
