#!/usr/bin/env bash
# Replay ASCII TUI demo frames in the terminal.
set -euo pipefail
clear_screen() { printf '\033[2J\033[H'; }
frames=(
$'sguala  5/6 online  refresh 10s  sort:config\n───────────────────────────────────────────────────────────────────────────────────────────────────\nGROUP      HOST      ADDR                    ST    CPU            MEM           DISK   LOAD    LAT\n── production ─────────────────────────────────────────────────────────────────────────────────────\nproduction web-01    deploy@10.0.0.11:22     ●  12.4%      43% 16.0G          61% /   0.42   48ms\nproduction web-02    deploy@10.0.0.12:22     ●   8.1%      38% 16.0G          56% /   0.31   52ms\nproduction db-01     ops@10.0.0.21:22        ●  64.7%      78% 16.0G          82% /   2.10   61ms\n── edge ───────────────────────────────────────────────────────────────────────────────────────────\nedge       bastion   jump@bastion.example:22 ●   3.2%      22% 16.0G          41% /   0.05   28ms\nedge       ci-runner ci@ci.example:22        ●  41.0%      55% 16.0G          70% /   1.20   90ms\n── lab ────────────────────────────────────────────────────────────────────────────────────────────\nlab        old-box   lab@192.168.9.9:22      ○      —              —              —      —      —\n\nk/↑ up • j/↓ down • enter detail • / search • o open ssh • t transfer • p set password • ? help …'
$'sguala  5/6 online  refresh 10s  sort:config\n───────────────────────────────────────────────────────────────────────────────────────────────────\nGROUP      HOST      ADDR                    ST    CPU            MEM           DISK   LOAD    LAT\n── production ─────────────────────────────────────────────────────────────────────────────────────\nproduction web-01    deploy@10.0.0.11:22     ●  12.4%      43% 16.0G          61% /   0.42   48ms\nproduction web-02    deploy@10.0.0.12:22     ●   8.1%      38% 16.0G          56% /   0.31   52ms\nproduction db-01     ops@10.0.0.21:22        ●  64.7%      78% 16.0G          82% /   2.10   61ms\n── edge ───────────────────────────────────────────────────────────────────────────────────────────\nedge       bastion   jump@bastion.example:22 ●   3.2%      22% 16.0G          41% /   0.05   28ms\nedge       ci-runner ci@ci.example:22        ●  41.0%      55% 16.0G          70% /   1.20   90ms\n── lab ────────────────────────────────────────────────────────────────────────────────────────────\nlab        old-box   lab@192.168.9.9:22      ○      —              —              —      —      —\n\nk/↑ up • j/↓ down • enter detail • / search • o open ssh • t transfer • p set password • ? help …'
$'sguala  5/6 online  refresh 10s  sort:config\n───────────────────────────────────────────────────────────────────────────────────────────────────\nGROUP      HOST      ADDR                    ST    CPU            MEM           DISK   LOAD    LAT\n── production ─────────────────────────────────────────────────────────────────────────────────────\nproduction web-01    deploy@10.0.0.11:22     ●  18.9%      43% 16.0G          61% /   0.42   48ms\nproduction web-02    deploy@10.0.0.12:22     ●   8.1%      38% 16.0G          56% /   0.31   52ms\nproduction db-01     ops@10.0.0.21:22        ●  71.2%      78% 16.0G          82% /   2.45   61ms\n── edge ───────────────────────────────────────────────────────────────────────────────────────────\nedge       bastion   jump@bastion.example:22 ●   3.2%      22% 16.0G          41% /   0.05   28ms\nedge       ci-runner ci@ci.example:22        ●  41.0%      55% 16.0G          70% /   1.20   90ms\n── lab ────────────────────────────────────────────────────────────────────────────────────────────\nlab        old-box   lab@192.168.9.9:22      ○      —              —              —      —      —\n\nk/↑ up • j/↓ down • enter detail • / search • o open ssh • t transfer • p set password • ? help …'
$'sguala  5/6 online  refresh 10s  sort:config  filter:"web" 2 hits\n/ web                                      \n───────────────────────────────────────────────────────────────────────────────────────────────────\nGROUP      HOST   ADDR                ST    CPU            MEM           DISK   LOAD    LAT\n── production ─────────────────────────────────────────────────────────────────────────────────────\nproduction web-01 deploy@10.0.0.11:22 ●  12.4%      43% 16.0G          61% /   0.42   48ms\nproduction web-02 deploy@10.0.0.12:22 ●   8.1%      38% 16.0G          56% /   0.31   52ms\n\n↑/↓ select · enter confirm · esc clear'
$'sguala  5/6 online  refresh 10s  sort:config\n───────────────────────────────────────────────────────────────────────────────────────────────────\nproduction · web-01  deploy@10.0.0.11:22\nCPU      12.4% ██░░░░░░░░░░░░░░░░░░\nMemory   43.2% ████████░░░░░░░░░░░░  6.9G / 16.0G\nLoad    0.42 0.38 0.34\nUptime  0h 0m\nLatency 48ms\nFetched 2026-09-09T23:15:27+08:00\n\nDisks\n  /                     61.0% ████████████░░░░░░░░  61.0G / 100.0G\n\nk/↑ up • j/↓ down • enter detail • / search • o open ssh • t transfer • p set password • ? help …'
$'sguala  5/6 online  refresh 10s  sort:config\n───────────────────────────────────────────────────────────────────────────────────────────────────\ntransfer  host web-01\n\nchoose action:\n> get (download)\n  put (upload)\n  sftp (interactive)\n\nenter confirm · esc back'
)
for f in "${frames[@]}"; do
  clear_screen
  printf '%s\n' "$f"
  sleep 1.2
done
printf '\n(demo done — run: asciinema play doc/tui.cast)\n'
